# This is a basic workflow to help you get started with Actions

name: Generate upgrade commit from *_full branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push to *_full branches
  push:
    branches: [ main_full, development_full ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.INTERSECTBOT_ACCESS_TOKEN }}

      - name: test
        run: echo ${{ env.GITHUB_SHA }}

      - name: Checkout upgrade branch
        run: git checkout ${GITHUB_REF_NAME/_full/_upgrade}

      # - name: Checkout modified files in full branch
      #   run: git checkout lodicolo/main_full -- $(git diff --name-only ${{ env.GITHUB_SHA }}~1 ${{ env.GITHUB_SHA }} | tr '\n' ' ')

      # - name: Generate commit
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     add_options: '-A'
      #     commit_message: "bot: automatically generating upgrade commit for ${{ env.GITHUB_SHA }}"
      #     commit_options: '--no-verify --signoff'
      #     commit_user_name: Intersect Bot
      #     commit_user_email: bot@ascension.dev
      #     skip_fetch: true
